name: jupysnaps
description: Extract images from .ipynb files with GUI and CLI supported.
version: 0.0.1
 repository: https://github.com/hippocampa/jupysnaps

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  flutter: ^3.8.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
